version: "3"
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: go-card.dev
    ports:
        - 8000:8000
    volumes:
        - .:/app
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password --init-file /db/migrate.sql
    volumes:
      - ./db/migrate.sql:/db/migrate.sql
    expose:
        - 3306
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=card_go_db
